# Generated by Django 5.1.1 on 2024-10-04 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile-picture/'),
        ),
    ]
