# Generated by Django 5.1.1 on 2024-09-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_icon', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('copyright_company', models.CharField(max_length=200)),
                ('copyright_year', models.CharField(max_length=4)),
            ],
        ),
    ]
