# Generated by Django 5.1.1 on 2024-09-30 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_settings',
            name='website_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='site_settings',
            name='website_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
