# Generated by Django 5.1.2 on 2025-04-26 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remainder'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_settings',
            name='invoice_logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
