# Generated by Django 5.1.1 on 2024-10-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_maintenance_cost'),
        ('order', '0021_order_extra_cost_order_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Profit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_sell', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
                ('maintenance_cost', models.ManyToManyField(to='dashboard.maintenance_cost')),
                ('orders', models.ManyToManyField(to='order.order')),
            ],
        ),
    ]
