# Generated by Django 5.1.2 on 2025-10-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_site_settings_invoice_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceColorDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_bg', models.CharField(blank=True, max_length=10, null=True)),
                ('footer_bg', models.CharField(blank=True, max_length=10, null=True)),
                ('footer_text_text', models.CharField(blank=True, max_length=10, null=True)),
                ('header_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('highlight_color', models.CharField(blank=True, max_length=10, null=True)),
                ('table_header_text', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
