# Generated by Django 5.1.2 on 2026-04-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_invoicecolordesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site_settings',
            name='copyright_year',
            field=models.CharField(max_length=10),
        ),
    ]
