# Generated by Django 5.1.1 on 2024-10-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_daily_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_profit',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
