# Generated by Django 5.1.1 on 2024-10-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_daily_profit_created_date_alter_daily_profit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_profit',
            name='created_date',
        ),
        migrations.AddField(
            model_name='daily_profit',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='daily_profit',
            name='date',
            field=models.DateField(auto_now_add=True, unique=True),
        ),
    ]
