# Generated by Django 5.1.1 on 2024-10-07 17:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_rename_date_daily_profit_profit_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_profit',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='daily_profit',
            name='profit_date',
        ),
        migrations.AddField(
            model_name='daily_profit',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
    ]
