# Generated by Django 5.1.1 on 2024-10-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_daily_profit_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_profit',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
