# Generated by Django 5.1.1 on 2024-10-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_daily_profit_date'),
        ('order', '0021_order_extra_cost_order_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_profit',
            name='maintenance_cost',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.maintenance_cost'),
        ),
        migrations.AlterField(
            model_name='daily_profit',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='order.order'),
        ),
    ]
