# Generated by Django 5.1.1 on 2024-10-08 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_daily_profit_maintenance_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_profit',
            name='maintenance_cost',
        ),
        migrations.RemoveField(
            model_name='daily_profit',
            name='orders',
        ),
    ]
