# Generated by Django 5.1.1 on 2024-10-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_remove_daily_profit_maintenance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance_cost',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance_cost',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
