# Generated by Django 5.1.1 on 2024-10-09 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_maintenance_cost_note_alter_maintenance_cost_cost'),
        ('order', '0022_order_design_file_alter_orderrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_profit',
            name='note',
        ),
        migrations.AddField(
            model_name='daily_profit',
            name='costs',
            field=models.ManyToManyField(blank=True, null=True, to='dashboard.maintenance_cost'),
        ),
        migrations.AddField(
            model_name='daily_profit',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, to='order.order'),
        ),
    ]
