# Generated by Django 5.1.1 on 2024-09-29 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('On The Way', 'On The Way'), ('Receive at delivery point', 'Receive at delivery point'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancel', 'Cancel')], max_length=50, null=True)),
                ('status_details', models.CharField(blank=True, max_length=600, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=50, null=True)),
                ('shipping_charge', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('paid_amount', models.IntegerField(blank=True, null=True)),
                ('item_name', models.CharField(blank=True, max_length=500, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_picture_link01', models.URLField(blank=True, max_length=500, null=True)),
                ('item_picture_link02', models.URLField(blank=True, max_length=500, null=True)),
                ('item_picture_link03', models.URLField(blank=True, max_length=500, null=True)),
                ('recipient_name', models.CharField(max_length=100)),
                ('recipient_phone_number', models.CharField(max_length=14)),
                ('delivery_address', models.CharField(max_length=500)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
