# Generated by Django 5.1.1 on 2024-09-29 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Shipped', 'Shipped'), ('On The Way', 'On The Way'), ('Receive at delivery point', 'Receive at delivery point'), ('Out For Delivery', 'Out For Delivery'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancel', 'Cancel')], default='Pending', max_length=50, null=True),
        ),
    ]
