# Generated by Django 5.1.2 on 2024-12-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Got Design', 'Got Design'), ('Processing', 'Processing'), ('Sample', 'Sample'), ('Packaging', 'Packaging'), ('Delivered', 'Delivered'), ('Return', 'Return')], max_length=50, null=True),
        ),
    ]
