# Generated by Django 5.1.1 on 2024-10-26 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_request_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Got Design', 'Got Design'), ('Cutting', 'Cutting'), ('Cutout Ready', 'Cutout Ready'), ('Engrave', 'Engrave'), ('Finishing', 'Finishing'), ('Packaging', 'Packaging'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ordercustomer',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
