# Generated by Django 5.1.2 on 2025-03-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercustomer',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
