# Generated by Django 5.1.2 on 2025-09-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_ordercustomer_email_orderrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='steadfast_parcel_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
