# Generated by Django 5.1.1 on 2024-09-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderupdatenote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Picked', 'Picked'), ('Shipped', 'Shipped'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancel', 'Cancel')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='item_picture_link04',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='item_picture_link05',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Received', 'Received'), ('Picked', 'Picked'), ('Shipped', 'Shipped'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Return', 'Return'), ('Cancel', 'Cancel')], default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='souece',
            field=models.CharField(choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Website', 'Website'), ('Others', 'Others')], default='Others', max_length=50),
        ),
    ]
