# Generated by Django 5.1.2 on 2025-02-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_product_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Design', 'Design'), ('Correction', 'Correction'), ('Call', 'Call'), ('Knock', 'Knock'), ('Other', 'Other'), ('Done', 'Done'), ('Hold', 'Hold'), ('Cancel', 'Cancel')], default='None', max_length=50),
        ),
    ]
