# Generated by Django 5.1.2 on 2024-11-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_orderrequest_request_created_by_order_urgent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
