# Generated by Django 5.1.1 on 2024-10-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordercustomer_second_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Got Design', 'Got Design'), ('Sample', 'Sample'), ('Cutting', 'Cutting'), ('Cutout Ready', 'Cutout Ready'), ('Engrave', 'Engrave'), ('Finishing', 'Finishing'), ('Packaging', 'Packaging'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Design', 'Design'), ('Correction', 'Correction'), ('Call', 'Call'), ('Knock', 'Knock'), ('Other', 'Other'), ('Done', 'Done'), ('Hold', 'Hold'), ('Cancel', 'Cancel'), ('Mockup', 'Mockup')], default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
