# Generated by Django 5.1.1 on 2024-10-01 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_status_order_company_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_price',
            new_name='advance_amount',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='create_date',
            new_name='order_date',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='item_description',
            new_name='remark',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_picture_link01',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_picture_link02',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_picture_link03',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_picture_link04',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_picture_link05',
        ),
        migrations.RemoveField(
            model_name='order',
            name='paid_amount',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='recipient_phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_charge',
        ),
        migrations.RemoveField(
            model_name='order',
            name='souece',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status_details',
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_charge',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='due_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('COD', 'COD'), ('Bkash', 'Bkash'), ('Nagod', 'Nagod'), ('Rocket', 'Rocket'), ('Upay', 'Upay')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='picture1',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='order',
            name='picture2',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='order',
            name='picture3',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='order',
            name='picture4',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='order',
            name='picture5',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Got Design', 'Got Design'), ('Cutting', 'Cutting'), ('Cutout Ready', 'Cutout Ready'), ('Engrave', 'Engrave'), ('Finishing', 'Finishing'), ('Packaging', 'Packaging'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], default='Unpaid', max_length=50),
        ),
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('souece', models.CharField(choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Website', 'Website'), ('Others', 'Others')], default='Others', max_length=50)),
                ('status', models.CharField(choices=[('None', 'None'), ('Design', 'Design'), ('Correction', 'Correction'), ('Call', 'Call'), ('Knock', 'Knock'), ('Other', 'Other'), ('Get Design', 'Get Design'), ('Done', 'Done'), ('Sample', 'Sample'), ('Hold', 'Hold'), ('Cancel', 'Cancel'), ('Mockup', 'Mockup')], default='None', max_length=50)),
                ('order_created', models.BooleanField(default=False)),
                ('remark', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('picture1', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('picture2', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('picture3', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('picture4', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('picture5', models.ImageField(blank=True, null=True, upload_to='pictures/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('request_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ManyToManyField(to='order.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(to='order.product'),
        ),
    ]
