# Generated by Django 5.1.2 on 2025-02-12 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_assign', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='request_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='work_assign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='order_request_assign', to=settings.AUTH_USER_MODEL),
        ),
    ]
