# Generated by Django 5.1.2 on 2025-11-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ordercustomer',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
