# Generated by Django 5.1.2 on 2024-11-05 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_orderrequest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
