# Generated by Django 5.1.2 on 2025-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_order_tracking_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
