# Generated by Django 5.1.2 on 2025-12-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_orderrequest_delivery_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteadFastWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('tracking_message', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Got Design', 'Got Design'), ('Processing', 'Processing'), ('Sample', 'Sample'), ('Token Print', 'Token Print'), ('Packaging', 'Packaging'), ('Delivered', 'Delivered'), ('Return', 'Return')], max_length=50, null=True),
        ),
    ]
