# Generated by Django 5.1.1 on 2024-10-01 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_delivery_date_alter_order_return_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='souece',
            new_name='source',
        ),
    ]
