# Generated by Django 5.1.2 on 2025-12-24 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_steadfastwebhooklog_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='steadfastwebhooklog',
            name='acocunt',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='steadfastwebhooklog',
            name='type',
            field=models.CharField(blank=True, choices=[('delivery_status', 'delivery_status'), ('tracking_update', 'tracking_update')], max_length=100, null=True),
        ),
    ]
