# Generated by Django 5.1.2 on 2024-11-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_order_order_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pathao_parcel_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
