# Generated by Django 5.1.2 on 2025-12-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_steadfastwebhooklog_acocunt_steadfastwebhooklog_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='steadfastwebhooklog',
            old_name='acocunt',
            new_name='account',
        ),
    ]
