# Generated by Django 5.1.1 on 2024-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_orderrequest_last_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderrequest',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
