# Generated by Django 6.0 on 2026-01-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_rename_acocunt_steadfastwebhooklog_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='steadfastwebhooklog',
            name='status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Got Design', 'Got Design'), ('Processing', 'Processing'), ('Sample', 'Sample'), ('Token Print', 'Token Print'), ('Packaging', 'Packaging'), ('Parcel Created', 'Parcel Created'), ('Delivered', 'Delivered'), ('Return', 'Return')], max_length=50, null=True),
        ),
    ]
