# Generated by Django 6.0 on 2026-01-04 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_steadfastwebhooklog_status_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('None', 'None'), ('Got Design', 'Got Design'), ('Processing', 'Processing'), ('Sample', 'Sample'), ('Token Print', 'Token Print'), ('Packaging', 'Packaging'), ('Parcel Created', 'Parcel Created'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Return', 'Return')], max_length=50, null=True),
        ),
    ]
