# Generated by Django 5.1.1 on 2024-10-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_orderrequest_tracking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderrequest',
            old_name='request_at',
            new_name='request_created_by',
        ),
        migrations.RemoveField(
            model_name='order',
            name='company',
        ),
        migrations.RemoveField(
            model_name='order',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picture4',
        ),
        migrations.RemoveField(
            model_name='order',
            name='picture5',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
    ]
