# Generated by Django 5.1.1 on 2024-10-02 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_rename_request_at_orderrequest_request_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.orderrequest'),
        ),
    ]
