# Generated by Django 5.1.1 on 2024-10-02 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_request_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='request_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.orderrequest'),
        ),
    ]
