# Generated by Django 5.1.1 on 2024-10-02 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_alter_order_request_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=20)),
                ('source', models.CharField(choices=[('Facebook', 'Facebook'), ('Whatsapp', 'Whatsapp'), ('Website', 'Website'), ('Others', 'Others')], default='Others', max_length=50)),
                ('logo', models.URLField(blank=True, max_length=300, null=True)),
                ('picture1', models.URLField(blank=True, max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ManyToManyField(to='order.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='order_customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='order.ordercustomer'),
        ),
    ]
