# Generated by Django 5.1.1 on 2024-10-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0015_ordercustomer_order_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Unpaid', 'Unpaid'), ('Partial', 'Partial'), ('Paid', 'Paid')], default='Unpaid', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('None', 'None'), ('Got Design', 'Got Design'), ('Cutting', 'Cutting'), ('Cutout Ready', 'Cutout Ready'), ('Engrave', 'Engrave'), ('Finishing', 'Finishing'), ('Packaging', 'Packaging'), ('Delivered', 'Delivered'), ('Return', 'Return')], default='Pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
