# Generated by Django 5.1.1 on 2024-10-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0016_alter_order_payment_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustomer',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
