# Generated by Django 5.1.1 on 2024-10-04 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0017_alter_ordercustomer_tracking_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercustomer',
            name='logo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
