# Generated by Django 5.1.1 on 2024-10-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0018_alter_ordercustomer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='ordercustomer',
            name='picture1',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ordercustomer',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='logo',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='picture1',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='picture2',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='picture3',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='picture4',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='picture5',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='tracking_ID',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
