# Generated by Django 5.1.1 on 2024-10-06 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0019_alter_order_tracking_id_alter_ordercustomer_picture1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_charge_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
