# Generated by Django 5.1.1 on 2024-10-09 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0022_order_design_file_alter_orderrequest_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_date',
            new_name='create_date',
        ),
    ]
