# Generated by Django 5.1.1 on 2024-10-09 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0023_rename_order_date_order_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='create_date',
            new_name='order_date',
        ),
    ]
